version: "3.8"

services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
    env_file:
      - ./env_files/mongo.env
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - DEFAULT_PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env_files/backend.env
    depends_on:
      - mongodb
  frontend:
    build: 
      context: ./frontend
      args:
        - DEFAULT_PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules
    depends_on:
      - backend
volumes:
  data: 
  logs: